### ISSUE TITLE
Can not scroll dates, month or year

### ISSUE THREAD

**Issue by Shvet** [ozcanalasalvar/picker#11]
I have implemented this library in  kotlin code. But it is always disabled. I can not scroll any of 3 pickers.
Edit:-
I found that it works fine in normal screen but inside RecyclerView adapter or viewpager it is not working.

**Comment by ozcanalasalvar** [comment]
Hi I released newer version of library. Now our target sdk version 34 and also have compose support. Please check currently published read me.
