### ISSUE TITLE
.pickerMode (DatePickerPopup.Builder) IS DEPRECATED?

### ISSUE THREAD

**Issue by gifandadelasty** [ozcanalasalvar/picker#16]
Hi, why is .pickerMode is Deprecated?

and please update the README.md for Implementation Gradle section (https://github.com/ozcanalasalvar/picker#implementation-gradle) to current version.. Thanks..

**Comment by ozcanalasalvar** [comment]
Hi I currently update read me file if you have any problem please inform me. There are lots of feature that I refactor. Sorry for delay.

**Comment by ozcanalasalvar** [comment]
If you have problem to migrate newer version of library. You can use this implementation for now.

implementation 'com.github.ozcanalasalvar:picker:Tag'

But I highly recommend to use lastest version.
