### ISSUE TITLE
Can you please make in cycle mode

### ISSUE THREAD

**Issue by NiharDodiya** [ozcanalasalvar/picker#3]
The date picker is not set in cycle mode like the current month date is 1 to 30, we scroll down 1 to 30 then stop scrolling on 30. I have to continually 1 to 30 again and again like IOS

**Comment by ozcanalasalvar** [comment]
Hi I released newer version of library. Now our target sdk version 34 and also have compose support. Please check currently published read me. The biggest news is library has infinite scroll feature
