### ISSUE TITLE
onDateSelected triggered in every scroll

### ISSUE THREAD

**Issue by Berkay92** [ozcanalasalvar/picker#32]
Right now, **onDateSelected** works like **onDateChanged** as it is triggered every time we scroll any of the sliders.

In some cases, we just need to open the date picker dialog and get the final selected Date after user clicks OK. So, maybe it would be great if we have these two options as callbacks? (**onDateSelected** and **onDataChanged**)

**Comment by ozcanalasalvar** [comment]
Hi sir,  Thank for your tip. I'm going to consider your suggestion and publish the version for that feature as soon as possible. Thank for your feedback. If you have anything to ask, please don't hesitate to ask.

**Comment by ozcanalasalvar** [comment]
You can check release 2.0.7
