### ISSUE TITLE
Crashed:  .WheelTimePickerKt.WheelTimePicker(WheelTimePicker.kt:94)

### ISSUE THREAD

**Issue by harishp-scg** [ozcanalasalvar/picker#35]
Crash 

                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ozcanalasalvar/wheelview/SelectorOptions;

**Comment by ozcanalasalvar** [comment]
You should import both picker and wheelview library.

dependencies {
	implementation 'com.github.ozcanalasalvar.picker:datepicker:2.0.7'
	implementation 'com.github.ozcanalasalvar.picker:wheelview:2.0.7'

	//For view based UI's
	implementation 'androidx.compose.material3:material3:Tag'
}
